# Generated by Django 4.0.3 on 2022-04-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_status_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mess_code',
            field=models.IntegerField(default=0),
        ),
    ]
