# Generated by Django 4.0.3 on 2022-04-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_customer_mess_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mess_code',
            field=models.CharField(max_length=100),
        ),
    ]
