# Generated by Django 4.0.3 on 2022-04-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='store.size'),
        ),
    ]
