# Generated by Django 4.0.3 on 2022-04-24 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.size'),
        ),
    ]
