# Generated by Django 4.0.3 on 2022-04-29 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_product_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
