# Generated by Django 4.0.3 on 2022-05-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_product_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
