# Generated by Django 4.0.3 on 2022-05-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_productdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='product_detail',
        ),
    ]
