# Generated by Django 4.0.3 on 2022-05-08 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
