# Generated by Django 4.0.3 on 2022-05-08 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_rename_product_order_product_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productdetail'),
        ),
    ]
