# Generated by Django 4.0.3 on 2022-05-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='color',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
